# Краткое руководство по библиотеке Numpy

Сайт библиотеки - http://www.numpy.org/ 

Документация - https://numpy.org/doc/ 

Введение на русском языке - https://habr.com/ru/post/352678/ 

Введение - https://docs.scipy.org/doc/numpy/user/quickstart.html 

Другие тьюториалы по NumPy:
- Часть 1 - https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/
- Часть 2 - https://www.machinelearningplus.com/python/numpy-tutorial-python-part2/
- 101 упражнение по NumPy - https://www.machinelearningplus.com/python/101-numpy-exercises-python/ 
- 100 упражнение по NumPy - http://www.labri.fr/perso/nrougier/teaching/numpy.100/ 
- The Best Tutorial for Beginners (Kaggle) - https://www.kaggle.com/getting-started/71679

## Введение в массивы Numpy 

https://numpy.org/doc/1.20/user/absolute_beginners.html

Массивы Numpy реализованы в виде структур языка С и принципиально отличаются от списков Python.

In [1]:
import numpy as np

### Создание массивов и размерности

In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Количество элементов
arr1.size

6

In [4]:
# Количество измерений
arr1.ndim

2

In [5]:
# Количество элементов по измерениям
arr1.shape

(2, 3)

In [6]:
# Изменение размерности
arr1.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# ValueError: cannot reshape array of size 6 into shape (4,2)
# arr1.reshape((4,2))

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Примеры добавления измерений
flat_arr = np.array([1, 2, 3, 4, 5, 6])
print(flat_arr.shape)
flat_arr 

(6,)


array([1, 2, 3, 4, 5, 6])

In [10]:
# Трансформация в вектор-строку с помощью np.newaxis
row_vector = flat_arr[np.newaxis, :]
print(row_vector.shape)
row_vector

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [11]:
# Трансформация в вектор-строку с помощью np.expand_dims
np.expand_dims(flat_arr, axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
# Трансформация в вектор-столбец с помощью np.newaxis
col_vector = flat_arr[:, np.newaxis]
print(col_vector.shape)
col_vector

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
# Трансформация в вектор-столбец с помощью np.expand_dims
np.expand_dims(flat_arr, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
# Транспонирование
arr1, arr1.T, arr1.T.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [15]:
# Превращаем в плоский массив
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

### Индексация

In [16]:
# трехмерная матрица
flat_3d = [111,112,113,121,122,123,131,132,133, \
          211,212,213,221,222,223,231,232,233, \
          311,312,313,321,322,323,331,332,333]
arr_3d = np.array(flat_3d).reshape((3,3,3))
arr_3d

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [17]:
# трехмерная матрица (все значения)
arr_3d[:,:,:]

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [18]:
arr_3d[0:1,:,:]

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]]])

In [19]:
arr_3d[:,0:1,:]

array([[[111, 112, 113]],

       [[211, 212, 213]],

       [[311, 312, 313]]])

In [20]:
arr_3d[:,:,0:1]

array([[[111],
        [121],
        [131]],

       [[211],
        [221],
        [231]],

       [[311],
        [321],
        [331]]])

In [21]:
arr_3d[1:3,1:3,1:3]

array([[[222, 223],
        [232, 233]],

       [[322, 323],
        [332, 333]]])

In [22]:
# Оставить два элемента от конца
arr_3d[-2:,:,:]

array([[[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [23]:
# Убрать два элемента от конца
arr_3d[:-2,:,:]

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]]])

In [24]:
# Присвоение значения
arr_3d[0,0,0] = 333
arr_3d

array([[[333, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

### Фильтры

In [25]:
fa = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
fa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# фильтр реализуется как массив логических значений
f1 = fa < 5
f1

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
f2 = fa % 2 == 0
f2

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [28]:
# при наложении фильтра возвращается плоский массив
fa[f2]

array([ 2,  4,  6,  8, 10, 12])

In [29]:
fa[fa % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

### Векторизация вычислений

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr3 = np.array([[1,2],[5,3],[4,6]])
arr3

array([[1, 2],
       [5, 3],
       [4, 6]])

In [33]:
arr3.max()

6

In [34]:
arr3.max(axis=0)

array([5, 6])

In [35]:
arr3.max(axis=1)

array([2, 5, 6])

In [36]:
# Умножение матриц
arr1, arr1.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [37]:
# Поэлементное умножение
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
np.multiply(arr1, arr1)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [39]:
# Матричное умножение
np.matmul(arr1, arr1.T)

array([[14, 32],
       [32, 77]])

In [40]:
np.matmul(arr1.T, arr1)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [41]:
arr1 @ arr1.T

array([[14, 32],
       [32, 77]])

### Уникальные значения

In [42]:
arr4 = np.array([1,1,1,2,3,2,2,2,3,3,3])
arr4

array([1, 1, 1, 2, 3, 2, 2, 2, 3, 3, 3])

In [43]:
np.unique(arr4)

array([1, 2, 3])

In [44]:
# В какой позиции в первый раз встречаются уникальные значения
np.unique(arr4, return_index=True)

(array([1, 2, 3]), array([0, 3, 4], dtype=int64))

In [45]:
# Сколько раз встречаются уникальные значения
np.unique(arr4, return_counts=True)

(array([1, 2, 3]), array([3, 4, 4], dtype=int64))

In [46]:
arr4

array([1, 1, 1, 2, 3, 2, 2, 2, 3, 3, 3])

In [47]:
arr4let_str = 'abc'
arr4let = list(map(lambda i: arr4let_str[i-1], arr4))
arr4let

['a', 'a', 'a', 'b', 'c', 'b', 'b', 'b', 'c', 'c', 'c']

In [48]:
arr4let_l, arr4let_c = np.unique(arr4let, return_counts=True)
list(zip(arr4let_l, arr4let_c))

[('a', 3), ('b', 4), ('c', 4)]

In [49]:
# И индексы и уникальные значения
np.unique(arr4, return_index=True, return_counts=True)

(array([1, 2, 3]),
 array([0, 3, 4], dtype=int64),
 array([3, 4, 4], dtype=int64))

## Дополнительные источники

- Список функций Numpy (по группам) -  https://numpy.org/doc/stable/reference/routines.html
- Список математических функций - https://numpy.org/doc/stable/reference/routines.math.html
- Типы данных - https://numpy.org/doc/1.20/user/basics.types.html
- Структурированные массивы (сложные типы данных) - https://numpy.org/doc/1.20/user/basics.rec.html
- Правила бродкастинга - https://numpy.org/doc/1.20/user/basics.broadcasting.html
- Пример обработки изображений с использованием Numpy - https://numpy.org/doc/1.20/user/tutorial-svd.html