# Некоторые возможности  библиотеки SciPy

SciPy — «библиотека для языка программирования Python с открытым исходным кодом, предназначенная для выполнения научных и инженерных расчётов» (Википедия).

Основная структура данных – массив NumPy.

Сайт библиотеки – https://www.scipy.org/ 

Документация - https://scipy.github.io/devdocs/index.html

Введение на русском языке – https://coderlessons.com/tutorials/python-technologies/uchitsia-stsipi/scipy-kratkoe-rukovodstvo (есть опечатки при переводе)

Пособие по решению оптимизационных задач – https://habr.com/ru/post/439288/ 

## Разреженные матрицы

Если набор данных слишком велик и содержит много пустых значений, то можно использовать разреженные матрицы:
- https://docs.scipy.org/doc/scipy/reference/sparse.html
- http://scipy-lectures.org/advanced/scipy_sparse/index.html 
- https://rushter.com/blog/scipy-sparse-matrices/ (простое введение)
- https://matteding.github.io/2019/04/25/sparse-matrices/ (иллюстрированное руководство)

In [1]:
from scipy import sparse
import numpy as np

In [2]:
# Случайные значения
r1 = sparse.random(15, 15)
r1

<15x15 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in COOrdinate format>

In [3]:
r1.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.8862819 , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.       

In [4]:
# Определим степень разреженности матрицы
# Количество непустых элементов
r1.nnz

2

In [5]:
# Количество элементов матрицы
np.product(r1.shape), r1.shape[0] * r1.shape[1]

(225, 225)

In [6]:
# Степень разреженности матрицы в процентах
(r1.nnz / np.product(r1.shape)) * 100 

0.8888888888888888

In [7]:
# Формат COO
row = [1, 3, 0, 2, 3]
col = [1, 4, 2, 3, 3]
data = [2, 5, 9, 1, 333]
coo = sparse.coo_matrix((data, (row, col)), shape=(6, 7))
coo

<6x7 sparse matrix of type '<class 'numpy.int32'>'
	with 5 stored elements in COOrdinate format>

In [8]:
coo.todense()

matrix([[  0,   0,   9,   0,   0,   0,   0],
        [  0,   2,   0,   0,   0,   0,   0],
        [  0,   0,   0,   1,   0,   0,   0],
        [  0,   0,   0, 333,   5,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0]])

In [9]:
# Формат DOK
dok = sparse.dok_matrix((6, 7), dtype=int)
dok[(1,1)] = 2
dok[(3,4)] = 5
dok[(0,2)] = 9
dok[(2,3)] = 1
dok[(3,3)] = 333
dok

<6x7 sparse matrix of type '<class 'numpy.int32'>'
	with 5 stored elements in Dictionary Of Keys format>

In [10]:
dok.todense()

matrix([[  0,   0,   9,   0,   0,   0,   0],
        [  0,   2,   0,   0,   0,   0,   0],
        [  0,   0,   0,   1,   0,   0,   0],
        [  0,   0,   0, 333,   5,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0]])

In [11]:
# Формат CSR
data = [9, 2, 1, 333, 5]
col =  [2, 1, 3, 3, 4]
indptr = [0, 1, 2, 3, 5, 5, 5]
csr = sparse.csr_matrix((data, col, indptr), shape=(6, 7), dtype=int)
csr

<6x7 sparse matrix of type '<class 'numpy.int32'>'
	with 5 stored elements in Compressed Sparse Row format>

In [12]:
csr.todense()

matrix([[  0,   0,   9,   0,   0,   0,   0],
        [  0,   2,   0,   0,   0,   0,   0],
        [  0,   0,   0,   1,   0,   0,   0],
        [  0,   0,   0, 333,   5,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0]])

## Минимизация функций

https://scipy.github.io/devdocs/tutorial/optimize.html

[Функция Розенброка](https://ru.wikipedia.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F_%D0%A0%D0%BE%D0%B7%D0%B5%D0%BD%D0%B1%D1%80%D0%BE%D0%BA%D0%B0) - в примерах используется вариант данной функции в 5-мерном пространстве.